# Generated by Django 2.2.10 on 2020-02-22 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200222_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='institution',
        ),
    ]
