# Generated by Django 2.2.10 on 2020-02-22 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_curriculum_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='posted_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='curriculum', to='app.Member'),
        ),
    ]
