# Generated by Django 2.2.10 on 2020-02-22 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_bit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=1000)),
                ('bit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='app.Bit')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='app.Member')),
            ],
        ),
    ]
