# Generated by Django 2.2.10 on 2020-02-24 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200224_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='designation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='member',
            name='institution',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='member', to='app.Institution'),
        ),
    ]
