# Generated by Django 2.2.8 on 2020-02-24 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_member_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bit',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bit', to='app.File'),
        ),
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_path', to='app.File'),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='app.Curriculum')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='app.Member')),
            ],
        ),
    ]
