# Generated by Django 2.2.10 on 2020-03-04 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20200224_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='app.Topic')),
            ],
        ),
        migrations.CreateModel(
            name='Teach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='bit',
            options={'ordering': ['-last_modified']},
        ),
        migrations.AlterModelOptions(
            name='curriculum',
            options={'ordering': ['-last_modified']},
        ),
        migrations.RemoveField(
            model_name='bit',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='bit',
            name='url',
        ),
        migrations.RemoveField(
            model_name='curriculum',
            name='institution',
        ),
        migrations.AddField(
            model_name='bit',
            name='bit_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bit',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='bit',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='bit',
            name='text',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='comment',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='curriculum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='app.Curriculum'),
        ),
        migrations.AddField(
            model_name='comment',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='upvote',
            name='curriculum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upvote', to='app.Curriculum'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='bit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='app.Bit'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum', to='app.Subject'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='curriculum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='app.Curriculum'),
        ),
        migrations.AlterField(
            model_name='upvote',
            name='bit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upvote', to='app.Bit'),
        ),
        migrations.DeleteModel(
            name='FileType',
        ),
        migrations.AddField(
            model_name='teach',
            name='curriculum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teach', to='app.Curriculum'),
        ),
        migrations.AddField(
            model_name='teach',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teach', to='app.Member'),
        ),
        migrations.AddField(
            model_name='changelog',
            name='bit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changelog', to='app.Bit'),
        ),
        migrations.AddField(
            model_name='changelog',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changelog', to='app.Comment'),
        ),
        migrations.AddField(
            model_name='changelog',
            name='curriculum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changelog', to='app.Curriculum'),
        ),
        migrations.AddField(
            model_name='changelog',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changelog', to='app.Member'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='app.Subject'),
        ),
        migrations.AddField(
            model_name='upvote',
            name='changelog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upvote', to='app.ChangeLog'),
        ),
    ]
