# Generated by Django 2.2.10 on 2020-03-05 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20200304_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curriculum',
            old_name='topic',
            new_name='subject',
        ),
    ]
