# Generated by Django 2.2.10 on 2020-03-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20200304_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='bit',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='bit',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
