# Generated by Django 2.2.10 on 2020-03-05 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_bit_posted_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curriculum',
            old_name='topic',
            new_name='subject',
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(choices=[('docx', 'Microsoft Word document'), ('pdf', 'PDF File'), ('zip', 'Compressed file (zip)'), ('video', 'Video file')], default=None, null=True, upload_to=''),
        ),
    ]
