# Generated by Django 2.2.10 on 2020-03-05 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20200305_0213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={},
        ),
        migrations.AddField(
            model_name='member',
            name='full_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='bit',
            name='bit_type',
            field=models.CharField(choices=[('docx', 'Microsoft Word document'), ('pdf', 'PDF File'), ('zip', 'Compressed file (zip)'), ('video', 'Video file'), ('url', 'Weblink (URL)')], max_length=100),
        ),
        migrations.AlterField(
            model_name='bit',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bit',
            name='file',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='bit', to='app.File'),
        ),
        migrations.AlterField(
            model_name='bit',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='bit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changelog', to='app.Bit'),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='comment',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='changelog', to='app.Comment'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
    ]
