# Generated by Django 2.2.10 on 2020-03-05 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20200305_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member', to='app.Institution'),
        ),
    ]
