# Generated by Django 2.2.10 on 2020-03-05 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20200305_0327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changelog',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='changelog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='app.ChangeLog'),
        ),
        migrations.AlterField(
            model_name='bit',
            name='bit_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bit',
            name='file',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='member',
            name='institution',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='Institution',
        ),
    ]
