# Generated by Django 2.2.10 on 2020-03-06 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20200305_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='changelog',
            name='subject',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changelog', to='app.Subject'),
        ),
    ]
