# Generated by Django 2.2.10 on 2020-03-05 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20200305_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='bit',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='app.Bit'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='changelog',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='app.ChangeLog'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='curriculum',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='app.Curriculum'),
        ),
    ]
